export default {
  inputs: [
    {
      id: 'old_password',
      placeholder: '',
      type: 'password',
      label: 'Старый пароль',
      wrapperClass: 'input input_row',
      max: 20,
      min: 8,
      pattern: /[\w]+/,
      autocomplete: false,
      value: '',
    },
    {
      id: 'new_password',
      placeholder: '',
      type: 'password',
      label: 'Новый пароль',
      wrapperClass: 'input input_row',
      max: 20,
      min: 8,
      pattern: /[\w]+/,
      autocomplete: false,
      value: undefined,
    },
    {
      id: 'confirm_password',
      placeholder: '',
      type: 'password',
      label: 'Повторите новый пароль',
      wrapperClass: 'input input_row',
      max: 20,
      min: 8,
      pattern: /[\w]+/,
      autocomplete: false,
      value: undefined,
    },
  ],
  confirm: {
    id: 'save-password',
    label: 'сохранить',
  },
};
