export default {
  inputs: [
    {
      id: 'mail',
      placeholder: '',
      type: 'email',
      label: 'Почта',
      class: 'input',
      wrapperClass: 'input',
    },
    {
      id: 'login',
      placeholder: '',
      type: 'text',
      label: 'Логин',
      class: 'input',
      wrapperClass: 'input',
    },
    {
      id: 'first_name',
      placeholder: '',
      type: 'text',
      label: 'Имя',
      class: 'input',
      wrapperClass: 'input',
    },
    {
      id: 'second_name',
      placeholder: '',
      type: 'text',
      label: 'Фамилия',
      class: 'input',
      wrapperClass: 'input',
    },
    {
      id: 'phone',
      placeholder: '',
      type: 'phone',
      label: 'Телефон',
      class: 'input',
      wrapperClass: 'input',
    },
    {
      id: 'password',
      placeholder: '',
      type: 'password',
      label: 'Пароль',
      class: 'input',
      wrapperClass: 'input',
      max: 20,
      min: 8,
      pattern: /[\w]+/,
      autocomplete: false,
    },
    {
      id: 'confirm_password',
      placeholder: '',
      type: 'password',
      label: 'Подтверждение пароля',
      class: 'input',
      wrapperClass: 'input',
      max: 20,
      min: 8,
      pattern: /[\w]+/,
      autocomplete: false,
    },
  ],
  confirm: {
    label: 'Зарегистрироваться',
    id: 'register',
  },
  link: {
    label: 'Войти',
    href: '/login',
  },
};
